import sys
import os
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
from modules import designTool as dt
from modules import utils as m

airplane = dt.standard_airplane('my_airplane_1')
dt.geometry(airplane)
dt.plot3d(airplane)

W0_guess = 50150*dt.gravity
T0_guess = 0.3*W0_guess 

dt.thrust_matching(W0_guess, T0_guess, airplane)
dt.balance(airplane)

print(f"airplane['cm_w'] = {airplane['cm_w']}")
print(f"airplane['xm_w'] = {airplane['xm_w']}")
print("airplane['xnp'] = ",airplane['xnp'])
print(f"(xnp - xm_w)/cma = {(airplane['xnp'] - airplane['xm_w'])/airplane['cm_w']}")
print(f"airplane['x_mlg'] = {airplane['x_mlg']}")
print(f"airplane['W0'] = {airplane['W0']}")
print("airplane['xcg_fwd'] = ",airplane['xcg_fwd'])
print(f"(xcg_fwd - xm_w)/cma = {(airplane['xcg_fwd'] - airplane['xm_w'])/airplane['cm_w']}")
print("airplane['xcg_aft'] = ",airplane['xcg_aft'])
print(f"(xcg_aft - xm_w)/cma = {(airplane['xcg_aft'] - airplane['xm_w'])/airplane['cm_w']}")
print(f"airplane['W_w'] = {airplane['W_w']}") 
print(f"airplane['W_h'] = {airplane['W_h']}") 
print(f"airplane['W_v'] = {airplane['W_v']}") 
print(f"airplane['W_f'] = {airplane['W_f']}") 
print(f"airplane['W_nlg'] = {airplane['W_nlg']}") 
print(f"airplane['W_mlg'] = {airplane['W_mlg']}") 
print(f"airplane['W_eng'] = {airplane['W_eng']}") 
print(f"airplane['W_allelse'] = {airplane['W_allelse']}") 
print(f"airplane['xcg_w'] = {airplane['xcg_w']}")
print(f"airplane['xcg_h'] = {airplane['xcg_h']}")
print(f"airplane['xcg_v'] = {airplane['xcg_v']}")
print(f"airplane['xcg_f'] = {airplane['xcg_f']}")
print(f"airplane['xcg_nlg'] = {airplane['xcg_nlg']}")
print(f"airplane['xcg_mlg'] = {airplane['xcg_mlg']}")
print(f"(xcg_mlg - xm_w)/cma = {(airplane['xcg_mlg'] - airplane['xm_w'])/airplane['cm_w']}")
print(f"airplane['xcg_eng'] = {airplane['xcg_eng']}")
print(f"airplane['xcg_allelse'] = {airplane['xcg_allelse']}")
print(f"airplane['W_fuel'] = {airplane['W_fuel']}")
print(f"airplane['W_crew'] = {airplane['W_crew']}")
print(f"airplane['xcg_crew'] = {airplane['xcg_crew']}")
print(f"airplane['S_w'] = {airplane['S_w']}")
print(f"airplane['AR_w'] = {airplane['AR_w']}")
print(f"airplane['taper_w'] = {airplane['taper_w']}")
print(f"airplane['sweep_w'] = {airplane['sweep_w']}")
print(f"airplane['xr_w'] = {airplane['xr_w']}")
print(f"airplane['zr_w'] = {airplane['zr_w']}")
print(f"airplane['L_f'] = {airplane['L_f']}")
print(f"airplane['D_f'] = {airplane['D_f']}")
print(f"airplane['S_h'] = {airplane['S_h']}")
print(f"airplane['AR_h'] = {airplane['AR_h']}")
print(f"airplane['taper_h'] = {airplane['taper_h']}")
print(f"airplane['sweep_h'] = {airplane['sweep_h']}")
print(f"airplane['dihedral_h'] = {airplane['dihedral_h']}")
print(f"airplane['xr_h'] = {airplane['xr_h']}")
print(f"airplane['zr_h'] = {airplane['zr_h']}")
print("airplane['SM_fwd'] = ",airplane['SM_fwd'])
print("airplane['SM_aft'] = ",airplane['SM_aft'])
print("airplane['tank_excess'] = ",airplane['tank_excess'])
print("airplane['V_maxfuel'] = ",airplane['V_maxfuel'])
print("airplane['CLv'] = ",airplane['CLv'])